cmake_minimum_required(VERSION 3.24)
project(FlightRLContacts LANGUAGES CXX)
include(FetchContent)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(INTERPROCEDURAL_OPTIMIZATION OFF CACHE BOOL "" FORCE)
set(GENERATE_DEBUG_SYMBOLS OFF CACHE BOOL "" FORCE)
set(TARGET_HELLO_WORLD OFF CACHE BOOL "" FORCE)
set(TARGET_UNIT_TESTS OFF CACHE BOOL "" FORCE)
set(TARGET_PERFORMANCE_TEST OFF CACHE BOOL "" FORCE)
set(TARGET_SAMPLES OFF CACHE BOOL "" FORCE)
set(TARGET_VIEWER OFF CACHE BOOL "" FORCE)
set(DEBUG_RENDERER_IN_DEBUG_AND_RELEASE OFF CACHE BOOL "" FORCE)
set(PROFILER_IN_DEBUG_AND_RELEASE OFF CACHE BOOL "" FORCE)
FetchContent_Declare(jolt URL https://github.com/jrouwe/JoltPhysics/archive/0373ec0dd762e4bc2f6acdb08371ee84fa23c6db.tar.gz SOURCE_SUBDIR Build)
FetchContent_MakeAvailable(jolt)
add_library(flightrl_contacts SHARED contacts.cpp)
target_link_libraries(flightrl_contacts PRIVATE Jolt)
target_compile_features(flightrl_contacts PRIVATE cxx_std_17)
